# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: Paullina Chacin
first_name: Paullina
last_name: Chacin
email: # to be added
description: >
  High school junior passionate about STEM education, community service, and leadership.
  Portfolio showcasing academic achievements, volunteering, and extracurricular activities.
footer_text: >
  © 2024 Paullina Chacin. All rights reserved.
keywords: high-school-portfolio, college-applications, student-portfolio, paullina-chacin
lang: en
icon: 🎓

url: https://paulinachacin.com # Update when custom domain is configured
baseurl: "" # Leave blank for user pages (username.github.io)
last_updated: false

# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------

# Enable dark mode
enable_darkmode: true
darkmode_permanent: false # Allow users to toggle

# -----------------------------------------------------------------------------
# SEO & Social Media
# -----------------------------------------------------------------------------

# Open Graph / Social Media
twitter_username: # optional
og_image: /assets/images/og-image.svg # Social sharing image (1200x630px recommended)

# SEO
author: Paullina Chacin
twitter:
  card: summary_large_image
social:
  name: Paullina Chacin
  links:
    # - https://linkedin.com/in/your-profile
    # - https://github.com/your-username

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  volunteering:
    output: true
    permalink: /volunteering/:name/
  events:
    output: true
    permalink: /events/:name/
  activities:
    output: true
    permalink: /activities/:name/

# Default values for collections
defaults:
  - scope:
      path: ""
      type: "volunteering"
    values:
      layout: "collection-item"
  - scope:
      path: ""
      type: "events"
    values:
      layout: "collection-item"
  - scope:
      path: ""
      type: "activities"
    values:
      layout: "collection-item"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Kramdown options
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

# Sass/SCSS options
sass:
  sass_dir: _sass
  style: compressed

# Includes / Excludes
include: ['_pages']
exclude:
  - bin/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - LICENSE
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - samples/
  - docs/
  - CLAUDE.md
  - README.md

keep_files:
  - CNAME
  - .nojekyll

# Plugins
plugins:
  - jekyll-email-protect
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji

# -----------------------------------------------------------------------------
# Optional Features - All Disabled
# -----------------------------------------------------------------------------

enable_google_analytics: false
enable_google_verification: false

# Social media - TO BE ADDED
linkedin_username: # to be added
github_username: # optional
